apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-platform-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/production-gitops-platform-eks.git
    targetRevision: main
    path: manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
